-- ============================================================
-- Migration 006: Switch embedding model from nomic-embed-text
--                (768-dim) to bge-m3 (1024-dim, multilingual)
--
-- Run this in Supabase SQL Editor BEFORE restarting the backend.
-- All existing embeddings will be cleared (NULL) and must be
-- regenerated by running scripts/reembed_all.py afterwards.
-- ============================================================

-- Step 1: Drop old vector indexes (required before altering column types)
DROP INDEX IF EXISTS idx_document_chunks_embedding;
DROP INDEX IF EXISTS idx_wiki_pages_embedding;
DROP INDEX IF EXISTS idx_canonical_qa_embedding;
DROP INDEX IF EXISTS idx_answer_cache_embedding;

-- Step 2: Alter embedding columns from vector(768) → vector(1024)
--   Using NULL cast because old 768-dim vectors are incompatible
ALTER TABLE document_chunks ALTER COLUMN embedding TYPE vector(1024) USING NULL;
ALTER TABLE wiki_pages      ALTER COLUMN embedding TYPE vector(1024) USING NULL;
ALTER TABLE canonical_qa    ALTER COLUMN embedding TYPE vector(1024) USING NULL;
ALTER TABLE answer_cache    ALTER COLUMN embedding TYPE vector(1024) USING NULL;

-- Step 3: Recreate IVFFLAT indexes for 1024-dim vectors
--   (lists=100 is fine; increase to 200 if table grows > 500k rows)
CREATE INDEX IF NOT EXISTS idx_document_chunks_embedding
  ON document_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

CREATE INDEX IF NOT EXISTS idx_wiki_pages_embedding
  ON wiki_pages USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

CREATE INDEX IF NOT EXISTS idx_canonical_qa_embedding
  ON canonical_qa USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

CREATE INDEX IF NOT EXISTS idx_answer_cache_embedding
  ON answer_cache USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- Step 4: Update all RPC functions to accept vector(1024)

CREATE OR REPLACE FUNCTION match_document_chunks(
  query_embedding vector(1024),
  match_company_code text,
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id uuid,
  title text,
  source_url text,
  content text,
  similarity float
)
LANGUAGE sql STABLE
AS $$
  SELECT
    dc.id,
    dc.title,
    dc.source_url,
    dc.content,
    1 - (dc.embedding <=> query_embedding) AS similarity
  FROM document_chunks dc
  WHERE dc.company_code = match_company_code
    AND dc.embedding IS NOT NULL
    AND 1 - (dc.embedding <=> query_embedding) >= match_threshold
  ORDER BY dc.embedding <=> query_embedding ASC, dc.source_url ASC, dc.chunk_index ASC
  LIMIT match_count;
$$;

CREATE OR REPLACE FUNCTION match_wiki_pages(
  query_embedding vector(1024),
  match_company_code text,
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id uuid,
  title text,
  source_url text,
  content_markdown text,
  similarity float
)
LANGUAGE sql STABLE
AS $$
  SELECT
    wp.id,
    wp.title,
    null::text AS source_url,
    wp.content_markdown,
    1 - (wp.embedding <=> query_embedding) AS similarity
  FROM wiki_pages wp
  WHERE wp.company_code = match_company_code
    AND wp.embedding IS NOT NULL
    AND wp.status = 'published'
    AND 1 - (wp.embedding <=> query_embedding) >= match_threshold
  ORDER BY wp.embedding <=> query_embedding ASC, wp.title ASC
  LIMIT match_count;
$$;

CREATE OR REPLACE FUNCTION match_canonical_qa(
  query_embedding vector(1024),
  match_company_code text,
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id uuid,
  question text,
  answer text,
  similarity float
)
LANGUAGE sql STABLE
AS $$
  SELECT
    qa.id,
    qa.question,
    qa.answer,
    1 - (qa.embedding <=> query_embedding) AS similarity
  FROM canonical_qa qa
  WHERE qa.company_code = match_company_code
    AND qa.is_active = true
    AND qa.embedding IS NOT NULL
    AND 1 - (qa.embedding <=> query_embedding) >= match_threshold
  ORDER BY qa.embedding <=> query_embedding ASC, qa.priority ASC, qa.question ASC
  LIMIT match_count;
$$;

CREATE OR REPLACE FUNCTION match_answer_cache(
  query_embedding vector(1024),
  match_company_code text,
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id uuid,
  question text,
  answer text,
  similarity float
)
LANGUAGE sql STABLE
AS $$
  SELECT
    ac.id,
    ac.question,
    ac.answer,
    1 - (ac.embedding <=> query_embedding) AS similarity
  FROM answer_cache ac
  WHERE ac.company_code = match_company_code
    AND ac.embedding IS NOT NULL
    AND 1 - (ac.embedding <=> query_embedding) >= match_threshold
  ORDER BY ac.embedding <=> query_embedding ASC, ac.updated_at DESC
  LIMIT match_count;
$$;

-- Verification query (optional — run to confirm changes)
-- SELECT table_name, column_name, udt_name
-- FROM information_schema.columns
-- WHERE column_name = 'embedding' AND table_schema = 'public'
-- ORDER BY table_name;
